---
title: "Testat SNA"
subtitle: "js_440"
author: "Jule Steenhorst"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Edge-Attribute** \
id: \
from: \
to: \
weight: \
relation:

**Node-Attribute**\
id:\
name:\
age:\
education:\
religion:



```{r Netzwerk einlesen, fig.height=6, fig.width=10, message=FALSE, warning=TRUE, paged.print=FALSE}

library(igraph)

# Edge- und Nodelist vorbereiten
el <- read.csv("https://raw.githubusercontent.com/js440/Testat_js440/main/Testat_js440%20-%20Edgelist.csv", header=T, as.is=T, sep = ",")


nodes <- read.csv("https://raw.githubusercontent.com/js440/Testat_js440/main/Testat_js440%20-%20Nodelist.csv", header=T, as.is=T, sep = ",")

edgematrix <-as.matrix(el)

#igraph Objekt erstellen
transfervfb <- graph_from_data_frame(d=edgematrix, directed=T)
transfervfb
```

# Netzwerkvisualisierung

```{r Netzwerk visualisieren, fig.height=6, fig.width=10}

plot(transfervfb, 
		 asp=0,
     layout=layout_nicely,
     main="Netzwerk_transfervfb",
     sub="js_440",
     vertex.color="lightblue",
     vertex.size=4,
     vertex.frame.color=NA,
     edge.color="black", 
     edge.arrow.size=.8)
```
